# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio')),
                ('body', models.TextField(blank=True, null=True)),
                ('followup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=200)),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=200)),
                ('followup_sent', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.Action')),
            ],
        ),
        migrations.CreateModel(
            name='TwilioNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('alpha_id', models.BooleanField(default=False)),
                ('fallback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.Fallback')),
                ('followup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.Followup')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('subscribed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='outbound',
            name='from_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.TwilioNumber'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='to_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.User'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='from_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.User'),
        ),
        migrations.AddField(
            model_name='inbound',
            name='to_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.TwilioNumber'),
        ),
        migrations.AddField(
            model_name='action',
            name='twilio_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.TwilioNumber'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('twilio_number', 'keyword')]),
        ),
    ]
