# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_outbound_answered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reprompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='reprompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twilionumber',
            name='reprompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.Reprompt'),
        ),
    ]
