# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_auto_20170829_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='reprompt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
