# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_outbound_reprompt_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='action',
            name='body',
            field=models.TextField(blank=True, help_text='Overrides audio. Only add if no audio', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='followup',
            field=models.TextField(blank=True, help_text='Overrides default followup for phone number', null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='keyword',
            field=models.CharField(help_text='Word for user text in. Must be all lowercase.', max_length=50),
        ),
        migrations.AlterField(
            model_name='action',
            name='reprompt',
            field=models.TextField(blank=True, help_text='Overrides default reprompt for phone number', null=True),
        ),
        migrations.AlterField(
            model_name='fallback',
            name='body',
            field=models.TextField(help_text='Text message to be sent to user'),
        ),
        migrations.AlterField(
            model_name='fallback',
            name='name',
            field=models.CharField(help_text='Used for identification within admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='followup',
            name='body',
            field=models.TextField(help_text='Text message to be sent to user'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='name',
            field=models.CharField(help_text='Used for identification within admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='reprompt',
            name='body',
            field=models.TextField(help_text='Text message to be sent to user'),
        ),
        migrations.AlterField(
            model_name='reprompt',
            name='name',
            field=models.CharField(help_text='Used for identification within admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='twilionumber',
            name='fallback',
            field=models.ForeignKey(help_text='Default fallback for this phone number', null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.Fallback'),
        ),
        migrations.AlterField(
            model_name='twilionumber',
            name='followup',
            field=models.ForeignKey(help_text='Default followup for this phone number', null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.Followup'),
        ),
        migrations.AlterField(
            model_name='twilionumber',
            name='number',
            field=models.CharField(help_text='Create number in Twilio before entering here. Include plus sign and country code. ie +1', max_length=20),
        ),
        migrations.AlterField(
            model_name='twilionumber',
            name='reprompt',
            field=models.ForeignKey(help_text='Default reprompt for this phone number', null=True, on_delete=django.db.models.deletion.CASCADE, to='interactions.Reprompt'),
        ),
    ]
